export const gamesData = [
  {
    Name: "Intellivision Lives!",
    Platform: "GC",
    Year_of_Release: "2004",
    Genre: "Misc",
    Publisher: "Crave Entertainment",
    NA_Sales: "0.05",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.06",
  },
  {
    Name: "Momotarou Dentetsu World",
    Platform: "DS",
    Year_of_Release: "2010",
    Genre: "Misc",
    Publisher: "Hudson Soft",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.19",
    Other_Sales: "0",
    Global_Sales: "0.19",
  },
  {
    Name: "Championship Surfer",
    Platform: "PS",
    Year_of_Release: "2000",
    Genre: "Sports",
    Publisher: "Mattel Interactive",
    NA_Sales: "0.03",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.06",
    Critic_Score: "57",
    Critic_Count: "5",
    Developer: "Krome Studios",
  },
  {
    Name: "Starcraft 64",
    Platform: "N64",
    Year_of_Release: "2000",
    Genre: "Strategy",
    Publisher: "Nintendo",
    NA_Sales: "0.13",
    EU_Sales: "0.03",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.16",
  },
  {
    Name: "Lalaloopsy",
    Platform: "DS",
    Year_of_Release: "2011",
    Genre: "Simulation",
    Publisher: "Activision",
    NA_Sales: "0.51",
    EU_Sales: "0.1",
    JP_Sales: "0",
    Other_Sales: "0.06",
    Global_Sales: "0.66",
    Developer: "Activision",
  },
  {
    Name: "Uta no * Prince-Sama: All Star",
    Platform: "PSP",
    Year_of_Release: "2013",
    Genre: "Action",
    Publisher: "Broccoli",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.12",
    Other_Sales: "0",
    Global_Sales: "0.12",
  },
  {
    Name: "LEGO Racers",
    Platform: "PS",
    Year_of_Release: "1999",
    Genre: "Racing",
    Publisher: "LEGO Media",
    NA_Sales: "0.2",
    EU_Sales: "0.14",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.36",
  },
  {
    Name: "Stunt Race FX",
    Platform: "SNES",
    Year_of_Release: "1993",
    Genre: "Racing",
    Publisher: "Nintendo",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.35",
    Other_Sales: "0",
    Global_Sales: "0.35",
  },
  {
    Name: "Petz Sports",
    Platform: "Wii",
    Year_of_Release: "2008",
    Genre: "Simulation",
    Publisher: "Ubisoft",
    NA_Sales: "0.42",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0.04",
    Global_Sales: "0.46",
  },
  {
    Name: "Disgaea D2: A Brighter Darkness",
    Platform: "PS3",
    Year_of_Release: "2013",
    Genre: "Role-Playing",
    Publisher: "Nippon Ichi Software",
    NA_Sales: "0.09",
    EU_Sales: "0",
    JP_Sales: "0.1",
    Other_Sales: "0.02",
    Global_Sales: "0.21",
    Critic_Score: "74",
    Critic_Count: "37",
    User_Score: "8.1",
    User_Count: "61",
    Developer: "Nippon Ichi Software",
  },
  {
    Name: "7 Wonders: Treasures of Seven",
    Platform: "DS",
    Year_of_Release: "2011",
    Genre: "Puzzle",
    Publisher: "Avanquest",
    NA_Sales: "0.01",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.03",
  },
  {
    Name: "Guitar Hero: On Tour",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Misc",
    Publisher: "Activision",
    NA_Sales: "2.1",
    EU_Sales: "1.01",
    JP_Sales: "0.01",
    Other_Sales: "0.35",
    Global_Sales: "3.46",
    Critic_Score: "71",
    Critic_Count: "70",
    User_Score: "8.8",
    User_Count: "29",
    Developer: "Vicarious Visions",
  },
  {
    Name: "Blood Wake",
    Platform: "XB",
    Year_of_Release: "2001",
    Genre: "Shooter",
    Publisher: "Microsoft Game Studios",
    NA_Sales: "0.43",
    EU_Sales: "0.12",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.57",
    Critic_Score: "71",
    Critic_Count: "30",
    User_Score: "7.5",
    User_Count: "13",
    Developer: "Stormfront Studios",
  },
  {
    Name: "Backbreaker",
    Platform: "X360",
    Year_of_Release: "N/A",
    Genre: "Sports",
    Publisher: "Unknown",
    NA_Sales: "0.17",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.18",
    Critic_Score: "54",
    Critic_Count: "29",
    User_Score: "7.6",
    User_Count: "68",
    Developer: "NaturalMotion",
  },
  {
    Name: "Beautiful Katamari",
    Platform: "X360",
    Year_of_Release: "2007",
    Genre: "Puzzle",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0.14",
    EU_Sales: "0.02",
    JP_Sales: "0.15",
    Other_Sales: "0.02",
    Global_Sales: "0.32",
    Critic_Score: "73",
    Critic_Count: "52",
    User_Score: "7",
    User_Count: "40",
    Developer: "Now Production",
  },
  {
    Name: "NHL Rock the Rink",
    Platform: "PS",
    Year_of_Release: "1999",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "0.14",
    EU_Sales: "0.1",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.26",
  },
  {
    Name: "Jumper: Griffin's Story",
    Platform: "Wii",
    Year_of_Release: "2008",
    Genre: "Action",
    Publisher: "Eidos Interactive",
    NA_Sales: "0.08",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.09",
    Critic_Score: "28",
    Critic_Count: "5",
    User_Score: "2.5",
    User_Count: "11",
    Developer: "Collision Studios",
  },
  {
    Name: "Digimon World: Dawn / Dusk",
    Platform: "DS",
    Year_of_Release: "2007",
    Genre: "Role-Playing",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0.12",
    EU_Sales: "0",
    JP_Sales: "0.18",
    Other_Sales: "0.01",
    Global_Sales: "0.31",
  },
  {
    Name: "MVP Baseball 2003",
    Platform: "PS2",
    Year_of_Release: "2003",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "0.51",
    EU_Sales: "0.4",
    JP_Sales: "0",
    Other_Sales: "0.13",
    Global_Sales: "1.04",
    Critic_Score: "81",
    Critic_Count: "22",
    User_Score: "8.9",
    User_Count: "17",
    Developer: "EA Sports",
  },
  {
    Name: "Mirror's Edge Catalyst",
    Platform: "XOne",
    Year_of_Release: "2016",
    Genre: "Platform",
    Publisher: "Electronic Arts",
    NA_Sales: "0.09",
    EU_Sales: "0.06",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.16",
    Critic_Score: "72",
    Critic_Count: "46",
    User_Score: "4.4",
    User_Count: "266",
    Developer: "EA DICE",
  },
  {
    Name: "Fairy Tail: Portable Guild",
    Platform: "PSP",
    Year_of_Release: "2010",
    Genre: "Fighting",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.11",
    Other_Sales: "0",
    Global_Sales: "0.11",
  },
  {
    Name: "NASCAR The Game: Inside Line",
    Platform: "X360",
    Year_of_Release: "2012",
    Genre: "Racing",
    Publisher: "Activision",
    NA_Sales: "0.09",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.1",
    Critic_Score: "72",
    Critic_Count: "7",
    User_Score: "3.4",
    User_Count: "27",
    Developer: "Eutechnyx",
  },
  {
    Name: "Queen's Gate: Spiral Chaos",
    Platform: "PSP",
    Year_of_Release: "2011",
    Genre: "Role-Playing",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.14",
    Other_Sales: "0",
    Global_Sales: "0.14",
  },
  {
    Name: "PES 2009: Pro Evolution Soccer",
    Platform: "PS3",
    Year_of_Release: "2008",
    Genre: "Sports",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "0.11",
    EU_Sales: "1.33",
    JP_Sales: "0.4",
    Other_Sales: "0.26",
    Global_Sales: "2.11",
  },
  {
    Name: "Ghost in the Shell: Stand Alone Complex",
    Platform: "PSP",
    Year_of_Release: "2005",
    Genre: "Adventure",
    Publisher: "Atari",
    NA_Sales: "0.06",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.07",
    Critic_Score: "61",
    Critic_Count: "23",
    User_Score: "7.4",
    User_Count: "14",
    Developer: "G-Artists",
  },
  {
    Name: "Lock On: Modern Air Combat",
    Platform: "PC",
    Year_of_Release: "2003",
    Genre: "Simulation",
    Publisher: "Ubisoft",
    NA_Sales: "0",
    EU_Sales: "0.03",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.03",
    Critic_Score: "76",
    Critic_Count: "20",
    User_Score: "7.5",
    User_Count: "549",
    Developer: "Eagle Dynamics",
  },
  {
    Name: "Rabbids: Alive & Kicking",
    Platform: "X360",
    Year_of_Release: "2011",
    Genre: "Misc",
    Publisher: "Ubisoft",
    NA_Sales: "0.15",
    EU_Sales: "0.11",
    JP_Sales: "0",
    Other_Sales: "0.03",
    Global_Sales: "0.29",
  },
  {
    Name: "Pokemon Card GB2: Here Comes Team GR!",
    Platform: "GB",
    Year_of_Release: "2001",
    Genre: "Strategy",
    Publisher: "Nintendo",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.89",
    Other_Sales: "0",
    Global_Sales: "0.89",
  },
  {
    Name: "Lego Star Wars: The Force Awakens",
    Platform: "PS4",
    Year_of_Release: "2016",
    Genre: "Action",
    Publisher: "Warner Bros. Interactive Entertainment",
    NA_Sales: "0.16",
    EU_Sales: "0.43",
    JP_Sales: "0.01",
    Other_Sales: "0.11",
    Global_Sales: "0.7",
    Critic_Score: "78",
    Critic_Count: "61",
    User_Score: "7.5",
    User_Count: "91",
    Developer: "TT Games",
  },
  {
    Name: "NBA 2K15",
    Platform: "PS4",
    Year_of_Release: "2014",
    Genre: "Sports",
    Publisher: "Take-Two Interactive",
    NA_Sales: "1.47",
    EU_Sales: "0.54",
    JP_Sales: "0.01",
    Other_Sales: "0.43",
    Global_Sales: "2.45",
    Critic_Score: "83",
    Critic_Count: "50",
    User_Score: "7",
    User_Count: "291",
    Developer: "Visual Concepts",
  },
  {
    Name: "Action Bass",
    Platform: "PS",
    Year_of_Release: "2000",
    Genre: "Action",
    Publisher: "Take-Two Interactive",
    NA_Sales: "0.64",
    EU_Sales: "0.43",
    JP_Sales: "0",
    Other_Sales: "0.07",
    Global_Sales: "1.14",
    Critic_Score: "51",
    Critic_Count: "8",
    Developer: "Vingt-et-un Systems",
  },
  {
    Name: "Bakugan Battle Brawlers: Defenders of the Core",
    Platform: "PS3",
    Year_of_Release: "2010",
    Genre: "Action",
    Publisher: "Activision",
    NA_Sales: "0.14",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.17",
    Critic_Score: "50",
    Critic_Count: "7",
    Developer: "Now Production",
  },
  {
    Name: "Tennis",
    Platform: "NES",
    Year_of_Release: "1984",
    Genre: "Sports",
    Publisher: "Nintendo",
    NA_Sales: "0.48",
    EU_Sales: "0.11",
    JP_Sales: "1.56",
    Other_Sales: "0.02",
    Global_Sales: "2.17",
  },
  {
    Name: "Nora to Koku no Koubou: Kiri no Mori no Majo",
    Platform: "DS",
    Year_of_Release: "2011",
    Genre: "Role-Playing",
    Publisher: "Atlus",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.05",
    Other_Sales: "0",
    Global_Sales: "0.05",
  },
  {
    Name: '"Flower',
    Platform: " Sun",
    Year_of_Release: ' and Rain"',
    Genre: "DS",
    Publisher: "2008",
    NA_Sales: "Adventure",
    EU_Sales: "Rising Star Games",
    JP_Sales: "0.06",
    Other_Sales: "0",
    Global_Sales: "0",
    Critic_Score: "0",
    Critic_Count: "0.07",
    User_Score: "54",
    User_Count: "37",
    Developer: "7.1",
  },
  {
    Name: "Pokémon Colosseum",
    Platform: "GC",
    Year_of_Release: "2003",
    Genre: "Role-Playing",
    Publisher: "Nintendo",
    NA_Sales: "1.21",
    EU_Sales: "0.57",
    JP_Sales: "0.7",
    Other_Sales: "0.07",
    Global_Sales: "2.54",
    Critic_Score: "73",
    Critic_Count: "37",
    User_Score: "8",
    User_Count: "89",
    Developer: "Genius Sonority Inc.",
  },
  {
    Name: "Disney's Meet the Robinsons",
    Platform: "GC",
    Year_of_Release: "2007",
    Genre: "Action",
    Publisher: "Disney Interactive Studios",
    NA_Sales: "0.03",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.04",
    Critic_Score: "68",
    Critic_Count: "5",
    Developer: "Avalanche Software",
  },
  {
    Name: "KimiKiss (ebKore+)",
    Platform: "PS2",
    Year_of_Release: "2008",
    Genre: "Adventure",
    Publisher: "Enterbrain",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.06",
    Other_Sales: "0",
    Global_Sales: "0.06",
  },
  {
    Name: "NBA Ballers",
    Platform: "XB",
    Year_of_Release: "2004",
    Genre: "Sports",
    Publisher: "Midway Games",
    NA_Sales: "0.37",
    EU_Sales: "0.11",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.51",
    Critic_Score: "82",
    Critic_Count: "35",
    User_Score: "8.1",
    User_Count: "8",
    Developer: "Midway",
  },
  {
    Name: "Crayon Shin-Chan: Densetsu o Yobu Omake no To Shukkugaan!",
    Platform: "GBA",
    Year_of_Release: "2006",
    Genre: "Action",
    Publisher: "Banpresto",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.07",
    Other_Sales: "0",
    Global_Sales: "0.07",
  },
  {
    Name: "Ford Racing",
    Platform: "PS",
    Year_of_Release: "2001",
    Genre: "Racing",
    Publisher: "Empire Interactive",
    NA_Sales: "0.48",
    EU_Sales: "0.33",
    JP_Sales: "0",
    Other_Sales: "0.06",
    Global_Sales: "0.86",
    Critic_Score: "53",
    Critic_Count: "4",
    User_Score: "5.8",
    User_Count: "4",
    Developer: "Toolbox Design",
  },
  {
    Name: "FIFA World Cup Germany 2006",
    Platform: "PSP",
    Year_of_Release: "2006",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "0.1",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.11",
    Critic_Score: "72",
    Critic_Count: "15",
    User_Score: "7.3",
    User_Count: "8",
    Developer: "EA Canada",
  },
  {
    Name: "Sesame Street: Once Upon A Monster",
    Platform: "X360",
    Year_of_Release: "2011",
    Genre: "Misc",
    Publisher: "Warner Bros. Interactive Entertainment",
    NA_Sales: "0.39",
    EU_Sales: "0.09",
    JP_Sales: "0",
    Other_Sales: "0.04",
    Global_Sales: "0.52",
    Critic_Score: "79",
    Critic_Count: "26",
    User_Score: "6.9",
    User_Count: "22",
    Developer: "Double Fine Productions",
  },
  {
    Name: "Red Bull BC One",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Misc",
    Publisher: "Playlogic Game Factory",
    NA_Sales: "0.08",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.09",
    Critic_Score: "48",
    Critic_Count: "15",
    User_Score: "5.3",
    User_Count: "8",
    Developer: "Smack Down Productions",
  },
  {
    Name: "Black Cat",
    Platform: "PS2",
    Year_of_Release: "2006",
    Genre: "Action",
    Publisher: "Capcom",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.01",
    Other_Sales: "0",
    Global_Sales: "0.01",
  },
  {
    Name: "SD Gundam: Scad Hammers",
    Platform: "Wii",
    Year_of_Release: "2006",
    Genre: "Strategy",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.05",
    Other_Sales: "0",
    Global_Sales: "0.05",
  },
  {
    Name: "Homefront",
    Platform: "PC",
    Year_of_Release: "2011",
    Genre: "Shooter",
    Publisher: "THQ",
    NA_Sales: "0.11",
    EU_Sales: "0.1",
    JP_Sales: "0",
    Other_Sales: "0.03",
    Global_Sales: "0.24",
    Critic_Score: "70",
    Critic_Count: "36",
    User_Score: "5.5",
    User_Count: "531",
    Developer: "Digital Extremes",
  },
  {
    Name: "Mobile Suit Gundam 00: Gundam Meisters",
    Platform: "PS2",
    Year_of_Release: "2008",
    Genre: "Action",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.06",
    Other_Sales: "0",
    Global_Sales: "0.06",
  },
  {
    Name: "Mana Khemia: Alchemists of Al-Revis (JP sales)",
    Platform: "PS2",
    Year_of_Release: "2007",
    Genre: "Role-Playing",
    Publisher: "Nippon Ichi Software",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.04",
    Other_Sales: "0",
    Global_Sales: "0.04",
  },
  {
    Name: "Worms Forts: Under Siege",
    Platform: "PS2",
    Year_of_Release: "2004",
    Genre: "Strategy",
    Publisher: "Acclaim Entertainment",
    NA_Sales: "0.05",
    EU_Sales: "0.04",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.11",
    Critic_Score: "63",
    Critic_Count: "21",
    User_Score: "8",
    User_Count: "15",
    Developer: "Team 17",
  },
  {
    Name: "Tomb Raider: The Prophecy",
    Platform: "GBA",
    Year_of_Release: "2002",
    Genre: "Action",
    Publisher: "Ubisoft",
    NA_Sales: "0.1",
    EU_Sales: "0.04",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.14",
    Critic_Score: "66",
    Critic_Count: "20",
    User_Score: "8.8",
    User_Count: "13",
    Developer: "Ubisoft Milan",
  },
  {
    Name: "Disney's The Lion King: Simba's Mighty Adventure",
    Platform: "PS",
    Year_of_Release: "2000",
    Genre: "Action",
    Publisher: "Activision",
    NA_Sales: "0.08",
    EU_Sales: "0.06",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.15",
    Critic_Score: "30",
    Critic_Count: "5",
    User_Score: "6.9",
    User_Count: "9",
    Developer: "Paradox Development",
  },
  {
    Name: "Viva Pinata",
    Platform: "X360",
    Year_of_Release: "2006",
    Genre: "Simulation",
    Publisher: "Microsoft Game Studios",
    NA_Sales: "0.45",
    EU_Sales: "0.95",
    JP_Sales: "0.02",
    Other_Sales: "0.2",
    Global_Sales: "1.62",
    Critic_Score: "84",
    Critic_Count: "65",
    User_Score: "8",
    User_Count: "131",
    Developer: "Rare Ltd.",
  },
  {
    Name: "Real Time Conflict: Shogun Empires",
    Platform: "DS",
    Year_of_Release: "2005",
    Genre: "Strategy",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0.06",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.07",
    Critic_Score: "35",
    Critic_Count: "6",
    User_Score: "5.6",
    User_Count: "11",
    Developer: "Box Clever Interactive",
  },
  {
    Name: "Mame Goma 2: Uchi no Ko ga Ichiban!",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Simulation",
    Publisher: "Creative Core",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.06",
    Other_Sales: "0",
    Global_Sales: "0.06",
  },
  {
    Name: "Blitz: The League",
    Platform: "X360",
    Year_of_Release: "2006",
    Genre: "Sports",
    Publisher: "Midway Games",
    NA_Sales: "0.15",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.16",
    Critic_Score: "69",
    Critic_Count: "23",
    User_Score: "6.5",
    User_Count: "14",
    Developer: "Midway",
  },
  {
    Name: "Tom Clancy's Rainbow Six 3",
    Platform: "PS2",
    Year_of_Release: "2004",
    Genre: "Shooter",
    Publisher: "Ubisoft",
    NA_Sales: "0.4",
    EU_Sales: "0.31",
    JP_Sales: "0",
    Other_Sales: "0.1",
    Global_Sales: "0.81",
    Critic_Score: "70",
    Critic_Count: "34",
    User_Score: "8.2",
    User_Count: "17",
    Developer: "Ubisoft Shanghai",
  },
  {
    Name: "Shenmue",
    Platform: "DC",
    Year_of_Release: "1999",
    Genre: "Adventure",
    Publisher: "Sega",
    NA_Sales: "0.52",
    EU_Sales: "0.24",
    JP_Sales: "0.38",
    Other_Sales: "0.04",
    Global_Sales: "1.18",
    Critic_Score: "88",
    Critic_Count: "9",
    User_Score: "9.4",
    User_Count: "201",
    Developer: "Sega AM2",
  },
  {
    Name: "Dragon Ball Z: Burst Limit",
    Platform: "X360",
    Year_of_Release: "2008",
    Genre: "Fighting",
    Publisher: "Atari",
    NA_Sales: "0.24",
    EU_Sales: "0.18",
    JP_Sales: "0.03",
    Other_Sales: "0.05",
    Global_Sales: "0.49",
    Critic_Score: "72",
    Critic_Count: "50",
    User_Score: "7.6",
    User_Count: "41",
    Developer: '"Dimps Corporation',
  },
  {
    Name: "Mojo!",
    Platform: "PS2",
    Year_of_Release: "2003",
    Genre: "Puzzle",
    Publisher: "Mindscape",
    NA_Sales: "0.07",
    EU_Sales: "0.05",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.14",
  },
  {
    Name: "Marvel: Ultimate Alliance 2",
    Platform: "X360",
    Year_of_Release: "2009",
    Genre: "Role-Playing",
    Publisher: "Activision",
    NA_Sales: "0.68",
    EU_Sales: "0.15",
    JP_Sales: "0",
    Other_Sales: "0.08",
    Global_Sales: "0.9",
    Critic_Score: "73",
    Critic_Count: "75",
    User_Score: "7.3",
    User_Count: "82",
    Developer: "Vicarious Visions",
  },
  {
    Name: "NFL Street 2 Unleashed",
    Platform: "PSP",
    Year_of_Release: "2005",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "0.34",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.03",
    Global_Sales: "0.37",
    Critic_Score: "73",
    Critic_Count: "23",
    User_Score: "7.4",
    User_Count: "14",
    Developer: "EA Tiburon",
  },
  {
    Name: "Buck Bumble",
    Platform: "N64",
    Year_of_Release: "1998",
    Genre: "Action",
    Publisher: "Ubisoft",
    NA_Sales: "0.13",
    EU_Sales: "0.03",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.16",
  },
  {
    Name: "Infamous: First Light",
    Platform: "PS4",
    Year_of_Release: "2014",
    Genre: "Action",
    Publisher: "Sony Computer Entertainment",
    NA_Sales: "0",
    EU_Sales: "0.03",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.03",
    Critic_Score: "73",
    Critic_Count: "70",
    User_Score: "7.5",
    User_Count: "580",
    Developer: "Sucker Punch",
  },
  {
    Name: "MLB 09: The Show",
    Platform: "PSP",
    Year_of_Release: "2009",
    Genre: "Sports",
    Publisher: "Sony Computer Entertainment",
    NA_Sales: "0.24",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.26",
    Critic_Score: "78",
    Critic_Count: "12",
    User_Score: "6.9",
    User_Count: "7",
    Developer: "SCEA San Diego Studios",
  },
  {
    Name: "Wolfenstein",
    Platform: "PS3",
    Year_of_Release: "2009",
    Genre: "Shooter",
    Publisher: "Activision",
    NA_Sales: "0.25",
    EU_Sales: "0.27",
    JP_Sales: "0",
    Other_Sales: "0.11",
    Global_Sales: "0.63",
    Critic_Score: "71",
    Critic_Count: "58",
    User_Score: "7.4",
    User_Count: "77",
    Developer: '"id Software',
  },
  {
    Name: "Junjou Romanchika: Koi no Doki Doki Daisakusen",
    Platform: "PS2",
    Year_of_Release: "2008",
    Genre: "Adventure",
    Publisher: "Marvelous Interactive",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.01",
    Other_Sales: "0",
    Global_Sales: "0.01",
  },
  {
    Name: "Star Trek: Invasion",
    Platform: "PS",
    Year_of_Release: "2000",
    Genre: "Simulation",
    Publisher: "Activision",
    NA_Sales: "0.15",
    EU_Sales: "0.1",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.26",
    Critic_Score: "76",
    Critic_Count: "12",
    Developer: "Warthog",
  },
  {
    Name: "The Hustle: Detroit Streets",
    Platform: "PS2",
    Year_of_Release: "2006",
    Genre: "Sports",
    Publisher: "Activision",
    NA_Sales: "0.02",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.04",
    Critic_Score: "46",
    Critic_Count: "5",
    Developer: "Blade Interactive",
  },
  {
    Name: "F1 Championship Season 2000",
    Platform: "PS2",
    Year_of_Release: "2000",
    Genre: "Racing",
    Publisher: "Electronic Arts",
    NA_Sales: "0.06",
    EU_Sales: "0.05",
    JP_Sales: "0.03",
    Other_Sales: "0.02",
    Global_Sales: "0.16",
    Critic_Score: "71",
    Critic_Count: "11",
    Developer: "EA Sports",
  },
  {
    Name: "Pac-Man World Rally",
    Platform: "GC",
    Year_of_Release: "2006",
    Genre: "Racing",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0.06",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.08",
    Critic_Score: "57",
    Critic_Count: "10",
    User_Score: "7.8",
    User_Count: "4",
    Developer: "Smart Bomb Interactive",
  },
  {
    Name: "F-14 Tomcat",
    Platform: "GBA",
    Year_of_Release: "2001",
    Genre: "Action",
    Publisher: "Majesco Entertainment",
    NA_Sales: "0.5",
    EU_Sales: "0.19",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.7",
    Critic_Score: "67",
    Critic_Count: "8",
    Developer: "Virtucraft",
  },
  {
    Name: "Disney Art Academy",
    Platform: "3DS",
    Year_of_Release: "2016",
    Genre: "Action",
    Publisher: "Nintendo",
    NA_Sales: "0.02",
    EU_Sales: "0.01",
    JP_Sales: "0.08",
    Other_Sales: "0",
    Global_Sales: "0.11",
    Critic_Score: "72",
    Critic_Count: "16",
    User_Score: "6.8",
    User_Count: "5",
    Developer: "Headstrong Games",
  },
  {
    Name: "NASCAR 08",
    Platform: "PS2",
    Year_of_Release: "2007",
    Genre: "Racing",
    Publisher: "Electronic Arts",
    NA_Sales: "0.12",
    EU_Sales: "0.09",
    JP_Sales: "0",
    Other_Sales: "0.03",
    Global_Sales: "0.24",
    Critic_Score: "56",
    Critic_Count: "9",
    User_Score: "8.2",
    User_Count: "9",
    Developer: "EA Tiburon",
  },
  {
    Name: "Yamakawa Shuppansha Kanshuu: Shousetsu Sekaishi B",
    Platform: "DS",
    Year_of_Release: "2007",
    Genre: "Misc",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.08",
    Other_Sales: "0",
    Global_Sales: "0.08",
  },
  {
    Name: "Pony Friends: Mini Breeds Edition",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Simulation",
    Publisher: "Eidos Interactive",
    NA_Sales: "0.05",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.05",
    Developer: '"Eidos Interactive',
  },
  {
    Name: "Need for Speed (2015)",
    Platform: "PS4",
    Year_of_Release: "2015",
    Genre: "Racing",
    Publisher: "Electronic Arts",
    NA_Sales: "0.5",
    EU_Sales: "1.5",
    JP_Sales: "0.05",
    Other_Sales: "0.37",
    Global_Sales: "2.43",
  },
  {
    Name: "Black * Rock Shooter: The Game",
    Platform: "PSP",
    Year_of_Release: "2011",
    Genre: "Role-Playing",
    Publisher: "Unknown",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.15",
    Other_Sales: "0",
    Global_Sales: "0.15",
    Critic_Score: "66",
    Critic_Count: "19",
    User_Score: "7.2",
    User_Count: "39",
    Developer: '"Image Epoch',
  },
  {
    Name: "Pokemon Puzzle League",
    Platform: "N64",
    Year_of_Release: "2000",
    Genre: "Puzzle",
    Publisher: "Nintendo",
    NA_Sales: "0.36",
    EU_Sales: "0.08",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.45",
  },
  {
    Name: "Katekyoo Hitman Reborn! Dream Hyper Battle! Wii",
    Platform: "Wii",
    Year_of_Release: "2008",
    Genre: "Fighting",
    Publisher: "Marvelous Interactive",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.02",
    Other_Sales: "0",
    Global_Sales: "0.02",
  },
  {
    Name: "Roary the Racing Car",
    Platform: "DS",
    Year_of_Release: "2009",
    Genre: "Misc",
    Publisher: "Avanquest",
    NA_Sales: "0",
    EU_Sales: "0.08",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.09",
  },
  {
    Name: "Juiced 2: Hot Import Nights",
    Platform: "DS",
    Year_of_Release: "2007",
    Genre: "Racing",
    Publisher: "THQ",
    NA_Sales: "0.22",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.24",
    Critic_Score: "72",
    Critic_Count: "7",
    Developer: "Juice Games",
  },
  {
    Name: "Phantasy Star Online Episode I & II",
    Platform: "GC",
    Year_of_Release: "2002",
    Genre: "Role-Playing",
    Publisher: "Infogrames",
    NA_Sales: "0.23",
    EU_Sales: "0.06",
    JP_Sales: "0.16",
    Other_Sales: "0.01",
    Global_Sales: "0.45",
  },
  {
    Name: "Alpha Protocol",
    Platform: "X360",
    Year_of_Release: "2010",
    Genre: "Role-Playing",
    Publisher: "Sega",
    NA_Sales: "0.23",
    EU_Sales: "0.12",
    JP_Sales: "0",
    Other_Sales: "0.04",
    Global_Sales: "0.39",
    Critic_Score: "63",
    Critic_Count: "68",
    User_Score: "7.2",
    User_Count: "201",
    Developer: "Obsidian Entertainment",
  },
  {
    Name: "Castlevania: Harmony of Dissonance",
    Platform: "GBA",
    Year_of_Release: "2002",
    Genre: "Platform",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "0.16",
    EU_Sales: "0.06",
    JP_Sales: "0.04",
    Other_Sales: "0",
    Global_Sales: "0.26",
    Critic_Score: "87",
    Critic_Count: "27",
    User_Score: "8.2",
    User_Count: "39",
    Developer: "KCET",
  },
  {
    Name: "Cate West: The Vanishing Files",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Adventure",
    Publisher: "Oxygen Interactive",
    NA_Sales: "0.08",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.1",
    Critic_Score: "68",
    Critic_Count: "4",
    Developer: "Magellan Interactive",
  },
  {
    Name: "Kinect Joy Ride",
    Platform: "X360",
    Year_of_Release: "2010",
    Genre: "Racing",
    Publisher: "Microsoft Game Studios",
    NA_Sales: "0.92",
    EU_Sales: "0.39",
    JP_Sales: "0",
    Other_Sales: "0.12",
    Global_Sales: "1.43",
    Critic_Score: "52",
    Critic_Count: "46",
    User_Score: "5",
    User_Count: "20",
    Developer: "BigPark",
  },
  {
    Name: "Tennis no Oji-Sama Gyutto! DokiDoki Survival - Umi to Yama no Love Passion",
    Platform: "DS",
    Year_of_Release: "2011",
    Genre: "Sports",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.08",
    Other_Sales: "0",
    Global_Sales: "0.08",
  },
  {
    Name: "S.T.A.L.K.E.R.: Clear Sky",
    Platform: "PC",
    Year_of_Release: "2008",
    Genre: "Shooter",
    Publisher: "Deep Silver",
    NA_Sales: "0",
    EU_Sales: "0.03",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.04",
    Critic_Score: "75",
    Critic_Count: "47",
    User_Score: "7.7",
    User_Count: "478",
    Developer: "GSC Game World",
  },
  {
    Name: "Rock Band Track Pack: Classic Rock",
    Platform: "X360",
    Year_of_Release: "2009",
    Genre: "Misc",
    Publisher: "MTV Games",
    NA_Sales: "0.07",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.07",
    Critic_Score: "70",
    Critic_Count: "6",
    Developer: "Harmonix Music Systems",
  },
  {
    Name: "The Adventures of Darwin",
    Platform: "PS2",
    Year_of_Release: "2006",
    Genre: "Strategy",
    Publisher: "Essential Games",
    NA_Sales: "0.01",
    EU_Sales: "0",
    JP_Sales: "0.03",
    Other_Sales: "0",
    Global_Sales: "0.04",
    Critic_Score: "53",
    Critic_Count: "10",
    Developer: "Vingt-et-un Systems",
  },
  {
    Name: "New Play Control! Pikmin",
    Platform: "Wii",
    Year_of_Release: "2008",
    Genre: "Strategy",
    Publisher: "Nintendo",
    NA_Sales: "0.28",
    EU_Sales: "0.12",
    JP_Sales: "0.19",
    Other_Sales: "0.04",
    Global_Sales: "0.64",
  },
  {
    Name: "Harvest Moon: Tree of Tranquility",
    Platform: "Wii",
    Year_of_Release: "2007",
    Genre: "Simulation",
    Publisher: "Rising Star Games",
    NA_Sales: "0.67",
    EU_Sales: "0.03",
    JP_Sales: "0.06",
    Other_Sales: "0.05",
    Global_Sales: "0.82",
    Critic_Score: "65",
    Critic_Count: "18",
    User_Score: "8.2",
    User_Count: "28",
    Developer: "Marvelous Entertainment",
  },
  {
    Name: "Bottom of the 9th",
    Platform: "PS",
    Year_of_Release: "1996",
    Genre: "Sports",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "0.08",
    EU_Sales: "0.05",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.14",
  },
  {
    Name: "Gift: Prism",
    Platform: "PS2",
    Year_of_Release: "2006",
    Genre: "Adventure",
    Publisher: "Sweets",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.02",
    Other_Sales: "0",
    Global_Sales: "0.02",
  },
  {
    Name: "MLB 12: The Show",
    Platform: "PS3",
    Year_of_Release: "2012",
    Genre: "Sports",
    Publisher: "Sony Computer Entertainment",
    NA_Sales: "0.86",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.06",
    Global_Sales: "0.92",
    Critic_Score: "87",
    Critic_Count: "23",
    User_Score: "7.5",
    User_Count: "75",
    Developer: "SCEA San Diego Studios",
  },
  {
    Name: "Shin Chan: ¡Aventuras de Cine!",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Platform",
    Publisher: "505 Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.15",
    Other_Sales: "0",
    Global_Sales: "0.15",
  },
  {
    Name: "Bank Heist",
    Platform: "2600",
    Year_of_Release: "1982",
    Genre: "Action",
    Publisher: "20th Century Fox Video Games",
    NA_Sales: "0.32",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.34",
  },
  {
    Name: "Zoboomafoo: Leapin' Lemurs!",
    Platform: "PS",
    Year_of_Release: "2001",
    Genre: "Action",
    Publisher: "Encore",
    NA_Sales: "0.02",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.03",
  },
  {
    Name: "Just Cause 2",
    Platform: "PC",
    Year_of_Release: "2010",
    Genre: "Action",
    Publisher: "Square Enix",
    NA_Sales: "0",
    EU_Sales: "0.1",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.12",
    Critic_Score: "84",
    Critic_Count: "33",
    User_Score: "7.7",
    User_Count: "838",
    Developer: "Avalanche Studios",
  },
];
